# Generated by Django 4.1.3 on 2022-11-26 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board_game_web_sites', '0002_reviews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
    ]
