# Generated by Django 4.1.3 on 2022-12-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_game_web_sites', '0003_rename_reviews_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='my_review',
            field=models.TextField(max_length=250),
        ),
    ]
