# Generated by Django 4.1.3 on 2022-12-08 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board_game_web_sites', '0004_alter_review_my_review'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Board_game',
            new_name='Game',
        ),
    ]
