# Generated by Django 4.1.3 on 2022-12-08 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board_game_web_sites', '0006_remove_game_artists_remove_game_designers_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Game',
            new_name='Board_game',
        ),
    ]
