# Generated by Django 4.1.3 on 2022-12-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_game_web_sites', '0009_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board_game',
            name='players',
        ),
        migrations.AddField(
            model_name='board_game',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='board_game',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
