# Generated by Django 4.1.3 on 2022-12-11 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board_game_web_sites', '0010_remove_board_game_players_board_game_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='board_game',
            new_name='game',
        ),
    ]
