# Generated by Django 4.1.3 on 2022-12-11 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('board_game_web_sites', '0009_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBorrows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_borrows', to='board_game_web_sites.user')),
            ],
        ),
    ]
